### ISSUE TITLE
Vimを終了させる旨、記載する

### ISSUE THREAD

**Issue by koron** [koron/online-update#5]
更新を実行する際はVimをすべて終了させる旨、記載する。

**Comment by Jagua** [comment]
予め Vim を終了しておかないと付属の DLL が更新されなくて焦る（経験者）ので，記載はあったほうがいいです．

**Comment by koron** [comment]
こっちは終息して https://github.com/koron/netupvim でやってある(あっちは終了させなくて良い)ので、閉じます。
